version: '3.6'
services:
  php:
    container_name: "property-bundle"
    build:
      context: ./docker/php
    restart: "no"
    environment:
      - APP_SECRET=${APP_SECRET}
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
